# Added EBS volume to EC2 CloudFormation template
# Revision 2
# May 20, 2026
 
AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Elastic Compute Cloud (EC2) Template
Parameters:
  LatestAmiId:
    Type : "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      KeyName: !Ref AWS::AccountId
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: gp2
            DeleationOnTermination: false
            VolumeSize: 20
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"